services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - back-end/.env.test
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coin_manager_test"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

volumes:
  postgres-volume: