services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - back-end/.env.test
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume: